import time
import serial_comms

test = serial_comms.Communicator(baudrate=115200, generate_csv=False)
print('is busy:', test.isBusy())
print('is paused:', test._paused)
test.resume()
print('is paused:', test._paused)
test.pause()
print('is paused:', test._paused)
test.setPort(0)
print('port:', test.currentPort())
print('is busy:', test.isBusy())
test.autoFindPort("CH340")
print('port:', test.currentPort())
print('is busy:', test.isBusy())
print('baudate:', test._baudrate)

print('Waiting for message...')
time.sleep(2)
test.sendCommand('t 25')
test.checkSerial()
print('message available:', test.hasMessage())
print('message recieved:', test.readMessage())
print('message available:', test.hasMessage())
print('Waiting for next messages...')
time.sleep(1)
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())

time.sleep(0.5)
test.openCommandFile('throttle_cmds.txt')
test.resume()
test.checkSerial()

time.sleep(1)
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())
test.checkSerial()
print('message recieved:', test.readMessage())

test.close()